DROP TABLE IF EXISTS MESSAGE_DATA;

CREATE TABLE MESSAGE_DATA (
  MESSAGE_ID VARCHAR(25) PRIMARY KEY,
  MESSAGE_DATA CLOB NOT NULL,
  PUBLISHED_DATE DATE NOT NULL,
  PROCESSED_DATE DATE DEFAULT NULL
);